# -*- coding: utf-8 -*-
"""Capstone

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EuaYw-xE0ZxnakuV2WxnUf3VFXKmiZM-

# Import Library
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

"""# Cek Dataset"""

df = pd.read_csv('/content/exercise_met_500 - 2024_Adult_Compendium.csv')
df.head(100)

import random

rows_add = 800 - len(df)

# Daftar gerakan fokus hipertrofi
exercises_base = [
    ("Barbell Bench Press", "Chest"), ("Dumbbell Incline Press", "Chest"), ("Cable Crossover", "Chest"), ("Machine Fly", "Chest"),
    ("Pull-up", "Back"), ("Lat Pulldown", "Back"), ("Barbell Row", "Back"), ("Seated Cable Row", "Back"), ("T-Bar Row", "Back"),
    ("Overhead Press", "Shoulders"), ("Lateral Raise", "Shoulders"), ("Front Raise", "Shoulders"), ("Face Pull", "Shoulders"),
    ("Barbell Squat", "Legs"), ("Leg Press", "Legs"), ("Romanian Deadlift", "Legs"), ("Leg Extension", "Legs"), ("Leg Curl", "Legs"),
    ("Barbell Curl", "Arms"), ("Dumbbell Hammer Curl", "Arms"), ("Tricep Pushdown", "Arms"), ("Overhead Tricep Extension", "Arms"),
    ("Calf Raise", "Legs"), ("Crunch", "Core"), ("Hanging Leg Raise", "Core"), ("Russian Twist", "Core")
]

# Variasi repitisi dan set
variations = [
    "heavy weight, low reps (hypertrophy focus)",
    "moderate weight, moderate reps (hypertrophy focus)",
    "light weight, high reps (endurance/hypertrophy)",
    "eccentric overload phase",
    "drop sets",
    "super sets",
    "rest-pause training",
    "tempo training (slow negative)",
    "isometric holds",
    "machine-based, focused contraction",
    "free-weight, stabilizing muscles engaged",
    "smith machine, controlled path"
]

new_rows = []
start_id = df['#'].max() + 1
start_code = 10000

for i in range(rows_add):
  base_ex, muscle_group = random.choice(exercises_base)
  variation = random.choice(variations)
  desc = f'{base_ex}, {muscle_group} focus, {variation}'

  # MET (Training moderat - vigorous = 3.5 - 6.0)
  met = round(random.uniform(3.5, 6.0), 1)
  intensity = "Moderate" if met < 5.0 else "Vigorous"

  # Kalkulasi kalori
  cal_60 = int(met * 60 * 0.5)
  cal_70 = int(met * 70 * 0.5)
  cal_80 = int(met * 80 * 0.5)

  new_rows.append({
        '#': start_id + i,
        'Major_Heading': 'Resistance Training',
        'Activity_Code': start_code + i,
        'MET_Value': met,
        'Intensity_Level': intensity,
        'Goal_Tag': 'Muscle Gain',
        'Activity_Description': desc,
        'Cal_60kg_per_30min': cal_60,
        'Cal_70kg_per_30min': cal_70,
        'Cal_80kg_per_30min': cal_80
  })

# Gabungkan data asli dan data tambah
df_new = pd.DataFrame(new_rows)
df_combined = pd.concat([df, df_new], ignore_index=True)

# Simpan
output_path = 'exercise_800.csv'
df_combined.to_csv(output_path, index=False)
print(f"Dataset berhasil disimpan {output_path}")
print(f'Total baris saat ini: {len(df_combined)}')
print(df_combined['Goal_Tag'].value_counts())

df = pd.read_csv('/content/exercise_800.csv')
df.tail(10)

"""# EDA

### Load & Sanitize Data
"""

df = pd.read_csv('exercise_800.csv')
df

import seaborn as sns
import matplotlib.pyplot as plt

# 1. Visualisasi Kategorikal (Intensity)
sns.countplot(data=df, x='Intensity_Level')
plt.title('Jumlah Data per Intensitas')
plt.show()

# 2. Visualisasi Numerik (MET)
sns.histplot(df['MET_Value'], kde=True)
plt.title('Penyebaran Nilai MET')
plt.show()

# 3. Statistik Deskriptif
print(df['Intensity_Level'].value_counts())
print(df['MET_Value'].describe())

"""### Augmentasi Data"""

import random

# Tentukan jumlah
target_count = 400
current_counts = df['Intensity_Level'].value_counts()

# Tambahkan variatif kegiatan
light_activities = [
    ("Slow Walking", 2.0), ("Stretching", 2.3), ('Yoga Hatha', 2.5), ('Tai Chi', 3.0), ('Washing Dishes', 2.2), ('Light Office Work', 1.5)
]

sedentary_activities = [
    ('Sitting quietly', 1.3), ('Lying down, awake', 1.3), ('Meditation', 1.0), ('Reading while sitting', 1.3)
]

new_balanced_rows = []
start_id = df['#'].max() + 1

def augment_class(activity_list, intensity_label, current_num):
  added = 0
  needed = target_count - current_num
  if needed <= 0: return

  for i in range(needed):
    base_act, met = random.choice(activity_list)
    # Tambahkan sedikit MET
    met_varied = round(met + random.uniform(-0.2, 0.2), 1)

    new_balanced_rows.append({
        '#': start_id + len(new_balanced_rows),
        'Major_Heading': 'Miscellaneous' if intensity_label == 'Sedentary' else 'Conditioning Exercise',
        'Activity_Code': 20000 + len(new_balanced_rows),
        'MET_Value': met_varied,
        'Intensity_Level': intensity_label,
        'Goal_Tag': 'Health Maintenance',
        'Activity_Description': f'{base_act}, variation {i+1}',
        'Cal_60kg_per_30min': int(met_varied * 60 * 0.5),
        'Cal_70kg_per_30min': int(met_varied * 70 * 0.5),
        'Cal_80kg_oer_30min': int(met_varied * 80 * 0.5)
    })

augment_class(light_activities, 'Light', current_counts.get('Light', 0))
augment_class(sedentary_activities, 'Sedentary', current_counts.get("Sedentary", 0))

# Gabungkan
df_balanced = pd.concat([df, pd.DataFrame(new_balanced_rows)], ignore_index=True)

print("--- Distribusi Data Setelah Penyeimbangan ---")
print(df_balanced['Intensity_Level'].value_counts())

# Simpan kembali
df_balanced.to_csv('exercise_balanced_800.csv', index=False)

df = pd.read_csv('/content/exercise_balanced_800.csv')
df

import seaborn as sns
import matplotlib.pyplot as plt

# 1. Visualisasi Kategorikal (Intensity)
sns.countplot(data=df, x='Intensity_Level')
plt.title('Jumlah Data per Intensitas')
plt.show()

# 2. Visualisasi Numerik (MET)
sns.histplot(df['MET_Value'], kde=True)
plt.title('Penyebaran Nilai MET')
plt.show()

# 3. Statistik Deskriptif
print(df['Intensity_Level'].value_counts())
print(df['MET_Value'].describe())

# Cleaning (Hapus spasi di nama kolom)
df.columns = df.columns.str.strip()

# Missing values
df.isnull().sum()

# Statistik MET
df['MET_Value'].describe()

"""# Preprocessing"""

from sklearn.preprocessing import LabelEncoder, StandardScaler

le_heading = LabelEncoder()
le_intensity = LabelEncoder()
# ubah intensity level menjadi angka
df['Heading_Encoded'] = le_heading.fit_transform(df['Major_Heading'])
df['Intensity_Encoded'] = le_intensity.fit_transform(df['Intensity_Level'])

scaler = StandardScaler()
df['MET_Scaled'] = scaler.fit_transform(df[['MET_Value']])

df_final = df[['Activity_Description', 'MET_Value', 'Intensity_Encoded', 'MET_Scaled']]

# Save mapping
mapping_heading = dict(zip(le_heading.classes_, le_heading.transform(le_heading.classes_)))
mapping_intensity = dict(zip(le_intensity.classes_, le_intensity.transform(le_intensity.classes_)))
print(mapping)

def ai_recommender(user_weight, user_bmi):
  # Logic
  if user_bmi >= 30:
    target = "Light"
  elif user_bmi >= 25:
    target = 'Moderate'
  else:
    target = 'Vigorous'

  candidates = df[df['Intensity_Level'] == target]
  recommendation = candidates.sample(1).iloc[0]

  duration_min = 30
  calories = recommendation['MET_Value'] * user_weight * (duration_min/60)

  return {
      "Activity": recommendation['Activity_Description'],
      "Intensity": recommendation['Intensity_Level'],
      "Calories_Burned": round(calories, 2),
      "MET": recommendation['MET_Value']
  }

print(ai_recommender(90, 31.1))

df.info()

"""# Model

### Random Forest
"""

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# Tentukan X dan y
X = df[['MET_Value', 'Heading_Encoded']]
y = df['Intensity_Encoded']

# Split 80 20
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=100)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy Score: {accuracy:.2%}")

cm = confusion_matrix(y_test, y_pred, labels=model.classes_)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=model.classes_,
            yticklabels=model.classes_)
plt.title("Confusion Matrix: Prediksi Intensitas Olahraga")
plt.xlabel("Prediksi")
plt.ylabel('Aktual')
plt.show()

print(classification_report(y_test, y_pred))

"""### Neural Network"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from tensorflow.keras.layers import BatchNormalization

num_classes = len(le_intensity.classes_)

model = Sequential([
    Dense(512, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    BatchNormalization(),
    Dropout(0.2),
    Dense(256, activation='relu'),
    BatchNormalization(),
    Dropout(0.2),
    Dense(128, activation='relu'), # Hidden layer
    Dense(num_classes, activation='softmax') # Output dengan 3 kelas
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.summary()

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau

callbacks = [
    EarlyStopping(
        monitor='val_loss',
        patience=10,
        restore_best_weights=True
    ),
    ModelCheckpoint(
        'smartfit.keras',
        monitor='val_accuracy',
        save_best_only=True
    ),
    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,
        patience=0.3,
        min_lr=1e-4,
        verbose=1
    )
]

history = model.fit(
    X_train_scaled,
    y_train,
    epochs=15,
    validation_data=(X_test_scaled, y_test),
    callbacks=callbacks,
    batch_size=32,
    verbose=1
)

plt.style.use('ggplot')
plt.figure(figsize=(10, 5))
epochs_run = len(history.history['loss'])
plt.plot(np.arange(0, epochs_run), history.history['loss'], label='training')
plt.plot(np.arange(0, epochs_run), history.history['val_loss'], label='validation')
plt.title('Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

"""# Inference"""